import { Project } from "./interface";

export const PROJECTS: Project[] = [
  {
    id: "parcelkoy",
    title: "ParcelKoy",
    type: "Full Stack",
    highlights: [
      "Built a courier logistics platform managing the full parcel delivery lifecycle — pickup, rider assignment, hub routing, tracking, delivery confirmation, and COD settlement.",
      "RBAC: Merchant, Rider, Admin, and Super-Admin.",
      "Integrated a Gemini AI using Vercel AI SDK and tool-calling",
      "Full-stack architecture: Express.js modular backend with Next.js service layer → server actions → client data flow.",
    ],
    videoUrl: "https://www.youtube.com/watch?v=3o3RtMysLV0",
    frontendStack: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Tailwind CSS" },
      { id: 3, name: "Vercel AI SDK" },
    ],
    backendStack: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "Express.js" },
      { id: 3, name: "Prisma ORM" },
      { id: 4, name: "PostgreSQL" },
    ],
    liveUrl: "https://nexus-crm.example.com",
    githubUrlFrontend: "https://github.com/example/nexus-crm-frontend",
    githubUrlBackend: "https://github.com/example/nexus-crm-backend",
    deepDiveUrl: "/blog/nexus-crm-deep-dive",
    accentColor: "var(--primary)",
  },
  {
    id: "forge-api",
    title: "Forge API Gateway",
    type: "Full Stack",
    highlights: [
      "Self-hosted API gateway",
      "Visual route builder",
      "Live traffic analytics",
      "JWT middleware injection",
      "OAuth provider proxying",
    ],
    videoUrl: "https://www.youtube.com/watch?v=3o3RtMysLV0",
    frontendStack: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Tailwind CSS" },
    ],
    backendStack: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "Express.js" },
      { id: 3, name: "Prisma ORM" },
      { id: 4, name: "PostgreSQL" },
    ],
    liveUrl: "https://forge-api.example.com",
    githubUrlFrontend: "https://github.com/example/forge-api-frontend",
    githubUrlBackend: "https://github.com/example/forge-api-backend",
    deepDiveUrl: "/blog/forge-api-deep-dive",
    accentColor: "var(--primary)",
  },
  {
    id: "atlas-finance",
    title: "Atlas Finance Tracker",
    type: "Full Stack",
    highlights: [
      "Personal finance dashboard",
      "Bank-sync simulation",
      "AI-categorized transactions",
      "Monthly budget forecasting",
      "Beautiful chart-driven reports",
    ],
    videoUrl: "https://www.youtube.com/watch?v=3o3RtMysLV0",
    frontendStack: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Tailwind CSS" },
    ],
    backendStack: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "Express.js" },
      { id: 3, name: "Prisma ORM" },
      { id: 4, name: "PostgreSQL" },
    ],
    liveUrl: "https://atlas-finance.example.com",
    githubUrlFrontend: "https://github.com/example/atlas-finance-frontend",
    githubUrlBackend: "https://github.com/example/atlas-finance-backend",
    deepDiveUrl: "/blog/atlas-finance-deep-dive",
    accentColor: "var(--primary)",
  },
];
