import { Project } from "./interface";

export const PROJECTS: Project[] = [
  {
    id: "parcelkoy",
    title: "ParcelKoy",
    type: "Full Stack",
    highlights: [
      "Built a courier logistics platform managing the full parcel delivery lifecycle — pickup, rider assignment, hub routing, tracking, delivery confirmation, and COD settlement.",
      "RBAC: Merchant, Rider, Admin, and Super-Admin.",
      "Integrated a Gemini AI using Vercel AI SDK and tool-calling",
      "Full-stack architecture: Express.js modular backend with Next.js service layer → server actions → client data flow.",
    ],
    videoUrl: "https://youtu.be/IklS_Rqex-E",
    frontendStack: [
      { id: "parcel-koy-frontend-tech-1", name: "Next.js" },
      { id: "parcel-koy-frontend-tech-2", name: "Tailwind CSS" },
      {
        id: "parcel-koy-frontend-tech-3",
        name: "TanStack React (Query+Form+Table)",
      },
      { id: "parcel-koy-frontend-tech-4", name: "Zod" },
      { id: "parcel-koy-frontend-tech-5", name: "Axios" },
      { id: "parcel-koy-frontend-tech-6", name: "Vercel AI SDK" },
      { id: "parcel-koy-frontend-tech-7", name: "TypeScript" },
    ],
    backendStack: [
      { id: "parcel-koy-backend-tech-1", name: "Express.js" },
      { id: "parcel-koy-backend-tech-2", name: "Prisma ORM" },
      { id: "parcel-koy-backend-tech-3", name: "PostgreSQL" },
      { id: "parcel-koy-backend-tech-4", name: "Better-auth" },
      { id: "parcel-koy-backend-tech-5", name: "Zod" },
      { id: "parcel-koy-backend-tech-6", name: "TypeScript" },
      { id: "parcel-koy-backend-tech-7", name: "Modular Architecture" },
    ],
    liveUrl: "https://parcel-koy-frontend.vercel.app/",
    githubUrlFrontend: "https://github.com/iarafathossain/parcel-koy-frontend",
    githubUrlBackend: "https://github.com/iarafathossain/parcel-koy-backend",
    deepDiveUrl: "/parcel-koy",
    accentColor: "var(--primary)",
  },
  {
    id: "EduConnect",
    title: "EduConnect",
    type: "Full Stack",
    highlights: [
      "Developed a production-ready LMS connecting learners with expert tutors, supporting course creation with video tutorials, quizzes, and articles.",
      "Implemented AI-powered semantic vector search with personalized course recommendations, course relevance.",
      "Built an auto-progress tracking system with completion state management, improving learner retention rates.",
      "Integrated an AI support chatbot for real-time query handling, reducing repetitive support requests.",
      "Engineered multi-step course creation forms with DB persistence and resume-from-state for interrupted workflows.",
    ],
    videoUrl: "https://youtu.be/IklS_Rqex-E",
    frontendStack: [
      { id: "educonnect-frontend-tech-1", name: "next.js" },
      { id: "educonnect-frontend-tech-2", name: "tailwind css" },
      {
        id: "educonnect-frontend-tech-3",
        name: "tanStack react (query+form+table)",
      },
      { id: "educonnect-frontend-tech-4", name: "shadcn/ui" },
      { id: "educonnect-frontend-tech-5", name: "framer-motion" },
      { id: "educonnect-frontend-tech-6", name: "react-dropzone" },
      { id: "educonnect-frontend-tech-7", name: "react-quill" },
    ],
    backendStack: [
      { id: "educonnect-backend-tech-1", name: "next.js api routes" },
      { id: "educonnect-backend-tech-2", name: "next-auth" },
      { id: "educonnect-backend-tech-3", name: "mongoDB/mongoose" },
      { id: "educonnect-backend-tech-4", name: "typescript" },
      { id: "educonnect-backend-tech-5", name: "zod" },
      { id: "educonnect-backend-tech-6", name: "pdf-lib" },
      { id: "educonnect-backend-tech-7", name: "resend" },
    ],
    liveUrl: "https://forge-api.example.com",
    sourceCode: "https://github.com/iarafathossain/educonnect",
    accentColor: "var(--primary)",
  },
  {
    id: "FarmFresh",
    title: "FarmFresh",
    type: "Full Stack",
    highlights: [
      "Built a role-based agricultural marketplace featuring adaptive UI navigation and intercepted routing for user authentication.",
      "Merchant tools enabling farmers to manage inventory, execute full product CRUD operations, and track orders.",
      "Engineered an end-to-end checkout flow with smart cart management, simulated payments, live status tracking, and automated PDF receipts.",
      "Advanced filtering and searching capabilities for an optimized browsing experience.",
      "Designed a secure customer trust system featuring verified, post-delivery product reviews and flexible pre-confirmation order cancellations.",
    ],
    videoUrl: "https://www.youtube.com/watch?v=3o3RtMysLV0",
    frontendStack: [
      { id: "farmfresh-tech-1", name: "next.js" },
      { id: "farmfresh-tech-2", name: "tailwind css" },
      { id: "farmfresh-tech-3", name: "centralize design system" },
    ],
    backendStack: [
      { id: "farmfresh-tech-1", name: "next.js api routes" },
      { id: "farmfresh-tech-2", name: "next-auth" },
      { id: "farmfresh-tech-3", name: "mongoDB/mongoose" },
      { id: "farmfresh-tech-4", name: "typeScript" },
    ],
    liveUrl: "https://farmfresh.example.com",
    sourceCode: "https://github.com/iarafathossain/farmfresh",
    accentColor: "var(--primary)",
  },
];
